version: "3.8"

services:
  frontend:
    image: amilaresidovic/frontend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    image: amilaresidovic/backend:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@${RDS_ENDPOINT}:5432/app_db
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
